# -*- coding: utf-8 -*-
"""SeanTownsendIndividualProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zmUBiktWl3KVnt8afadbOcgSU5HLhCe4
"""

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns


#Keep line commented out durring editing for easier workflow
from google.colab import files
uploaded = files.upload()

#set up main frame, add drop.isna later after we get problems sorted out properly
ds = 'vgsales(data_fix).csv'
df = pd.read_csv(ds)
df.drop(df.columns[0], axis=1, inplace=True)

df.dropna()

#AI used to resolve copy error
# Start
df = df[df['Year'] <= 2016].copy()
# End
df = df[df['Year'] >= 1980].copy()

df['Year'] = df['Year'].astype(int)



#setting up important frames, first 4 are just column + total sales, sales frames are just dropping all other sales
#genre_platform is how to set up frames where data is needed to be structured for multiple variables
#AI used to show reset_index
publisher_sales = df.groupby('Publisher')['Global_Sales'].sum().sort_values(ascending=False).reset_index()
genre_sales = df.groupby('Genre')['Global_Sales'].sum().sort_values(ascending=False).reset_index()
platform_sales = df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).reset_index()
year_sales = df.groupby('Year')['Global_Sales'].sum().sort_values(ascending=False).reset_index()
na_sales = df.drop(columns=['EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']).sort_values(by='NA_Sales', ascending=False).reset_index()
eu_sales = df.drop(columns=['NA_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']).sort_values(by='EU_Sales', ascending=False).reset_index()
jp_sales = df.drop(columns=['NA_Sales', 'EU_Sales', 'Other_Sales', 'Global_Sales']).sort_values(by='JP_Sales', ascending=False).reset_index()
other_sales = df.drop(columns=['NA_Sales', 'EU_Sales', 'JP_Sales', 'Global_Sales']).sort_values(by='Other_Sales', ascending=False).reset_index()
genre_platform_sales = df.groupby(['Genre', 'Platform'])['Global_Sales'].sum().reset_index()

#SEAN INDIVIDUAL 1: What years were the most profitable overall?

# Frames
year_sales= year_sales.sort_values(by='Year', ascending=True)
ystop = year_sales.sort_values(by='Global_Sales', ascending=False).head(5)


# For ploting every year
plt.figure(figsize=(12, 6))
sns.barplot(data = year_sales, x='Year', y='Global_Sales', color='skyblue')
plt.title('Global Sales by Year')
plt.xlabel('Year')
plt.ylabel('Global Sales (in millions)')
plt.xticks(rotation=90)
plt.show()

# For plotting top years
plt.figure(figsize=(12, 6))
sns.barplot(data = ystop, x='Year', y='Global_Sales', color='skyblue', order=ystop['Year'])
plt.title('Top 5 Years by Global Sales')
plt.xlabel('Year')
plt.ylabel('Global Sales (in millions)')

s2008 = df[df['Year'] == 2008].sort_values(by='Global_Sales', ascending=False).head(3)
s2009 = df[df['Year'] == 2009].sort_values(by='Global_Sales', ascending=False).head(3)
s2007 = df[df['Year'] == 2007].sort_values(by='Global_Sales', ascending=False).head(3)
s2010 = df[df['Year'] == 2010].sort_values(by='Global_Sales', ascending=False).head(3)
s2006 = df[df['Year'] == 2006].sort_values(by='Global_Sales', ascending=False).head(3)

display (s2008)
display (s2009)
display (s2007)
display (s2010)
display (s2006)

#SEAN INDIVIDUAL 2: How does this differ between region and how different are the overall levels of profit for those years?

year_sales= year_sales.sort_values(by='Year', ascending=True)

# Set up frames
na_year_sales= na_sales.groupby('Year')['NA_Sales'].sum().reset_index()
eu_year_sales= eu_sales.groupby('Year')['EU_Sales'].sum().reset_index()
jp_year_sales= jp_sales.groupby('Year')['JP_Sales'].sum().reset_index()
other_year_sales= other_sales.groupby('Year')['Other_Sales'].sum().reset_index()

# Set up figure
plt.figure(figsize=(12, 6))
plt.xlabel('Year')
plt.ylabel('Sales (in Millions)')
plt.title('Regional Sales Over Time (1980-2016)')
plt.xticks(year_sales['Year'].astype(int), rotation=87)

# Plot each frame seperately to show all lines
plt.plot(na_year_sales['Year'], na_year_sales['NA_Sales'], marker='o', linestyle='-', color='green')
plt.plot(jp_year_sales['Year'], jp_year_sales['JP_Sales'], marker='o', linestyle='-', color='red')
plt.plot(eu_year_sales['Year'], eu_year_sales['EU_Sales'], marker='o', linestyle='-', color='blue')
plt.plot(other_year_sales['Year'], other_year_sales['Other_Sales'], marker='o', linestyle='-', color='purple')

# Plot legend
plt.legend(['NA Sales', 'JP Sales', 'EU Sales', 'Other Sales'])

plt.show()

# Set up second figure
fig, ax = plt.subplots(2,2, figsize=(20, 12))

# Sort each frame by sales rather than year
na_year_sales = na_year_sales.sort_values(by='NA_Sales', ascending=False).head(5)
jp_year_sales = jp_year_sales.sort_values(by='JP_Sales', ascending=False).head(5)
eu_year_sales = eu_year_sales.sort_values(by='EU_Sales', ascending=False).head(5)
other_year_sales = other_year_sales.sort_values(by='Other_Sales', ascending=False).head(5)

# Set up each plot, order by year to ensure data remains properly ordered when plotting
sns.barplot(data = na_year_sales, x='Year', y='NA_Sales', color='green', ax=ax[0,0], order=na_year_sales['Year'])
ax[0,0].set_title('Top Years for NA Sales')
ax[0,0].set_xlabel('Year')
ax[0,0].set_ylabel('NA Sales (in millions)')

sns.barplot(data = jp_year_sales, x='Year', y='JP_Sales', color='red', ax=ax[0,1], order=jp_year_sales['Year'])
ax[0,1].set_title('Top Years for JP Sales')
ax[0,1].set_xlabel('Year')
ax[0,1].set_ylabel('JP Sales (in millions)')

sns.barplot(data = eu_year_sales, x='Year', y='EU_Sales', color='blue', ax=ax[1,0], order=eu_year_sales['Year'])
ax[1,0].set_title('Top Years for EU Sales')
ax[1,0].set_xlabel('Year')
ax[1,0].set_ylabel('EU Sales (in millions)')

sns.barplot(data = other_year_sales, x='Year', y='Other_Sales', color='purple', ax=ax[1,1], order=other_year_sales['Year'])
ax[1,1].set_title('Top Years for Other Sales')
ax[1,1].set_xlabel('Year')
ax[1,1].set_ylabel('Other Sales (in millions)')

plt.tight_layout()
plt.show()

# Time Series LSTM for NA Sales
# Can LSTM be used to predict NA Sales (either per game or annual total)?

from sklearn.metrics import mean_squared_error, mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from sklearn.preprocessing import MinMaxScaler

# Using the setup in the posted Colab 'intro_time_series_lstm_lab.ipynb', set up a time series LSTM to predict how NA sales evolve over time



# ANYTHING RELATING TO SCALING WAS ADJUSTED BY GEMINI AS A FINAL CHECK TO SEE IF IT WAS POSSIBLE TO USE LSTM
# FOR MY PURPOSES

# Reestablish frame

na_year_sales= na_sales.groupby('Year')['NA_Sales'].sum().reset_index()

# Set up our frame - using the pre-aggregated na_year_sales DataFrame
series = na_year_sales['NA_Sales'].values.reshape(-1, 1)

# AI SCALING
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_series = scaler.fit_transform(series)

# Define the means to create a sequence using an array and a given length
def create_sequences(data_array, seq_length):

  X = []
  y = []

  for i in range(len(data_array) - seq_length):
    X.append(data_array[i:i+seq_length])
    y.append(data_array[i+seq_length])

  return np.array(X), np.array(y)

# define what will be used to create the sequence from the SCALED data
window_size = 3

X, y = create_sequences(scaled_series, window_size)

# Begin mapping training parameters
train_size = int(0.7 * len(X))
X_train = X[:train_size]
y_train = y[:train_size]
X_test = X[train_size:]
y_test = y[train_size:]

# Set parameters to proper shape
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

# define the model type
model = Sequential([
  LSTM(50, activation="tanh", input_shape=(window_size, 1)),
  Dense(1)
])

# Compile the model
model.compile(optimizer="adam", loss="mse")

# Train the model using data and defined parameters
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=3,
    validation_split=0.1,
    verbose=1
)

# Plot training and validation losses to analyze model effectiveness

plt.figure(figsize=(15, 10))
plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")
plt.title("Training and Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.show()

# Test Model
# AI SCALING
scaled_predictions = model.predict(X_test)

# Plot model vs data

# Test at original scale
# AI SCALING
y_test_original = scaler.inverse_transform(y_test)
predictions_original = scaler.inverse_transform(scaled_predictions)

plt.figure(figsize=(15, 10))
plt.plot(y_test_original, label="Actual")
plt.plot(predictions_original, label="Predicted")
plt.title("Actual vs Predicted NA Sales (Yearly Totals)")
plt.xlabel("Time Step (Years)")
plt.ylabel("NA Sales (in millions)")
plt.legend()
plt.show()

# Check numeric reliability through errors

# AI SCALING
# Inverse transform y_test and scaled_predictions to original scale for error calculation
y_test_original = scaler.inverse_transform(y_test)
predictions_original = scaler.inverse_transform(scaled_predictions)

mse = mean_squared_error(y_test_original, predictions_original)
mae = mean_absolute_error(y_test_original, predictions_original)

print("MSE (Original Scale):", mse)
print("MAE (Original Scale):", mae)

# Check errors in scaled data

mse = mean_squared_error(y_test, scaled_predictions)
mae = mean_absolute_error(y_test, scaled_predictions)

print("MSE (Original Scale):", mse)
print("MAE (Original Scale):", mae)